language: julia
os:
  - linux
  - osx
julia:
  - 0.7
  - 1.0
  - nightly
notifications:
  email: false
git:
  depth: 99999999
matrix:
  allow_failures:
after_success:
  # push coverage results to Coveralls
  - julia -e '(VERSION >= v"0.7" && using Pkg); Pkg.add("Coverage"); cd(Pkg.dir("Word2Vec")); using Coverage; Coveralls.submit(process_folder()); Codecov.submit(process_folder())'
